; config/settings.ini

[App]
; 애플리케이션 기본 설정
APP_NAME = FANUC-Turntable-Syncronizer  ; 앱 이름 (나중에 UI 제목 등에 씀)
VERSION = 1.0.0                         ; 버전 관리용
DEBUG = True                            ; 개발 중엔 True, 현장 배포 시 False로 바꿔서 로그 양 조절
LOG_DIR = logs                          ; 로그 파일이 저장될 폴더 이름

[TwinCAT]
; TwinCAT PLC 접속 정보
; 로컬 테스트 할 때: 127.0.0.1.1.1
; 현장에 있는 실제 장비 IP: 5.143.171.16.1.1

; AMS_NET_ID = 5.143.171.16.1.1 <- PLC 고유 주소
; PORT = 851                    <- TwinCAT3 기본 포트
; DEMO_MODE = False             <- 데모 모드 : PLC 없이 테스트할 때는 True로 바꾸면 된다
AMS_NET_ID = 5.143.171.16.1.1
PORT = 851
DEMO_MODE = False


[Robot]
; 로봇 관련 기본 설정
DEFAULT_SPEED = 100             ; 로봇 초기 속도


[TurnTable]
; TODO: 턴테이블 관련 넣기
